version: '3.8'

services:
  db1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: 'KOCHETOV_BPI215_1'
      POSTGRES_USER: 'KOCHETOV_BPI215'
      POSTGRES_PASSWORD: 'KOCHETOV_BPI215'
    volumes:
      - ./docker/db/config/KOCHETOV_BPI215_1:/var/lib/postgresql/data
      - ./docker/db/scripts/KOCHETOV_BPI215_1:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  db2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: 'KOCHETOV_BPI215_2'
      POSTGRES_USER: 'KOCHETOV_BPI215'
      POSTGRES_PASSWORD: 'KOCHETOV_BPI215'
    volumes:
      - ./docker/db/config/KOCHETOV_BPI215_2:/var/lib/postgresql/data
      - ./docker/db/scripts/KOCHETOV_BPI215_2:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  db3:
    image: postgres:14.5
    environment:
      POSTGRES_DB: 'KOCHETOV_BPI215_3'
      POSTGRES_USER: 'KOCHETOV_BPI215'
      POSTGRES_PASSWORD: 'KOCHETOV_BPI215'
    volumes:
      - ./docker/db/config/KOCHETOV_BPI215_3:/var/lib/postgresql/data
      - ./docker/db/scripts/KOCHETOV_BPI215_3:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
